apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-app

spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: sam021995/backend:v4
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:

        # =========================
        # DB CONFIG FROM CONFIGMAP
        # =========================
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST

        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_DATABASE

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_PORT

        # =========================
        # DB SECRETS
        # =========================
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        # =========================
        # APP INFO (FOR DASHBOARD)
        # =========================
        - name: APP_VERSION
          value: "v4"

        - name: ENVIRONMENT
          value: "production"
