apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: employee-app

spec:
  replicas: {{ .Values.frontend.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      annotations:
        manual-helm-test: "phase-3"
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: Always

        ports:
        - containerPort: 80