name: Application CI-CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "env/prod/frontend-app/**"
      - "env/prod/backend-api/**"
      - ".github/workflows/application-cicd.yml"

  workflow_dispatch:

concurrency:
  group: employee-app-prod
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 628658447302.dkr.ecr.eu-west-1.amazonaws.com
  FRONTEND_REPO: frontend
  BACKEND_REPO: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628658447302:role/GitHubActionsEKSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        run: |
          cd env/prod/frontend-app
          docker build \
            -t $ECR_REGISTRY/$FRONTEND_REPO:${{ github.run_number }} \
            -t $ECR_REGISTRY/$FRONTEND_REPO:latest .

      - name: Scan Frontend Image With Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.FRONTEND_REPO }}:${{ github.run_number }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Push Frontend Image
        run: |
          docker push $ECR_REGISTRY/$FRONTEND_REPO:${{ github.run_number }}
          docker push $ECR_REGISTRY/$FRONTEND_REPO:latest

      - name: Build Backend Image
        run: |
          cd env/prod/backend-api
          docker build \
            -t $ECR_REGISTRY/$BACKEND_REPO:${{ github.run_number }} \
            -t $ECR_REGISTRY/$BACKEND_REPO:latest .

      - name: Scan Backend Image With Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.BACKEND_REPO }}:${{ github.run_number }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: Push Backend Image
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPO:${{ github.run_number }}
          docker push $ECR_REGISTRY/$BACKEND_REPO:latest

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628658447302:role/GitHubActionsEKSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4


      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name three-tier-eks

      - name: Deploy Application Using Helm
        run: |
          helm upgrade employee-app ./env/prod/employee-app-chart \
            --install \
            --namespace employee-app \
            --set frontend.image.repository=$ECR_REGISTRY/$FRONTEND_REPO \
            --set frontend.image.tag=${{ github.run_number }} \
            --set backend.image.repository=$ECR_REGISTRY/$BACKEND_REPO \
            --set backend.image.tag=${{ github.run_number }} \
            --wait \
            --atomic \
            --timeout 5m

      - name: Verify Frontend Rollout
        run: |
          kubectl rollout status deployment/frontend -n employee-app --timeout=120s

      - name: Verify Backend Rollout
        run: |
          kubectl rollout status deployment/backend -n employee-app --timeout=120s
