name: Application CI-CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'env/prod/frontend-app/**'
      - 'env/prod/backend-api/**'
      - '.github/workflows/application-cicd.yml'

  workflow_dispatch:

concurrency:
  group: employee-app-prod
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 628658447302.dkr.ecr.eu-west-1.amazonaws.com
  FRONTEND_REPO: frontend
  BACKEND_REPO: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628658447302:role/GitHubActionsEKSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        run: |
          cd env/prod/frontend-app
          docker build \
            -t $ECR_REGISTRY/$FRONTEND_REPO:${{ github.run_number }} \
            -t $ECR_REGISTRY/$FRONTEND_REPO:latest .

      - name: Push Frontend Image
        run: |
          docker push $ECR_REGISTRY/$FRONTEND_REPO:${{ github.run_number }}
          docker push $ECR_REGISTRY/$FRONTEND_REPO:latest

      - name: Build Backend Image
        run: |
          cd env/prod/backend-api
          docker build \
            -t $ECR_REGISTRY/$BACKEND_REPO:${{ github.run_number }} \
            -t $ECR_REGISTRY/$BACKEND_REPO:latest .

      - name: Push Backend Image
        run: |
          docker push $ECR_REGISTRY/$BACKEND_REPO:${{ github.run_number }}
          docker push $ECR_REGISTRY/$BACKEND_REPO:latest

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628658447302:role/GitHubActionsEKSDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name three-tier-eks

      - name: Deploy Frontend
        run: |
          kubectl set image deployment/frontend frontend=$ECR_REGISTRY/$FRONTEND_REPO:${{ github.run_number }} -n employee-app

      - name: Verify Frontend Rollout With Rollback
        run: |
          kubectl rollout status deployment/frontend -n employee-app --timeout=120s || {
            echo "Frontend rollout failed. Rolling back..."
            kubectl rollout undo deployment/frontend -n employee-app
            kubectl rollout status deployment/frontend -n employee-app --timeout=120s
            exit 1
          }

      - name: Deploy Backend
        run: |
          kubectl set image deployment/backend backend=$ECR_REGISTRY/$BACKEND_REPO:${{ github.run_number }} -n employee-app

      - name: Verify Backend Rollout With Rollback
        run: |
          kubectl rollout status deployment/backend -n employee-app --timeout=120s || {
            echo "Backend rollout failed. Rolling back..."
            kubectl rollout undo deployment/backend -n employee-app
            kubectl rollout status deployment/backend -n employee-app --timeout=120s
            exit 1
          }